"""Bundle the Espruino module and an example into one paste-able file.

`require("BTHomeWritable")` only resolves once the module is published to
EspruinoDocs or dropped into the Web IDE's project folder. For bring-up and for
the hardware tests we want something that works with nothing but copy-paste, so
this inlines the module in a closure and appends the example.

`require("BTHome")` is left alone: the Web IDE fetches that one from
espruino.com automatically.

    python -m tools.build_espruino_bundle
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE = ROOT / "espruino" / "BTHomeWritable.js"
EXAMPLES = ROOT / "espruino" / "examples"
OUTPUT_DIR = ROOT / "espruino" / "dist"

HEADER = """/* bthome-writable — {example}, self-contained.
 *
 * GENERATED by tools/build_espruino_bundle.py. Do not edit: change
 * espruino/BTHomeWritable.js or espruino/examples/{example} and rebuild.
 *
 * Paste the whole file into the Espruino Web IDE's right-hand pane and send it
 * to a connected nRF52 board. `require("BTHome")` is fetched automatically by
 * the IDE; everything else is inlined here.
 */

"""


def bundle(example: Path) -> str:
    module_source = MODULE.read_text(encoding="utf-8")
    example_source = example.read_text(encoding="utf-8")

    # The example requires the module by name; inline it instead.
    example_source = example_source.replace(
        'var bw = require("BTHomeWritable");',
        "var bw = BTHomeWritable;",
    )

    return (
        HEADER.format(example=example.name)
        + "var BTHomeWritable = (function () {\n"
        + "  var exports = {};\n\n"
        + module_source
        + "\n  return exports;\n})();\n\n"
        + "/* --- "
        + example.name
        + " ".ljust(0)
        + " --- */\n\n"
        + example_source
    )


def strip_comments(source: str) -> str:
    """Remove comments and blank lines, leaving string literals alone.

    Espruino keeps the source text of every function in RAM, and this module is
    comment-heavy on purpose — which costs more than half the bundle on a
    64 kB device. This is not a minifier: it does not rename or reformat
    anything, so the result still reads like the original.

    It does not recognise regular-expression literals, which would be
    misparsed. Neither the module nor the examples contain one, and
    espruino/test/bundle.test.js runs the stripped bundle to prove it still
    behaves — that check lives on the JS side because it needs a JS engine.
    """
    out: list[str] = []
    i, n = 0, len(source)
    while i < n:
        char = source[i]
        if char in "\"'`":
            quote = char
            out.append(char)
            i += 1
            while i < n:
                if source[i] == "\\":
                    out.append(source[i : i + 2])
                    i += 2
                    continue
                out.append(source[i])
                if source[i] == quote:
                    i += 1
                    break
                i += 1
            continue
        if source.startswith("//", i):
            while i < n and source[i] != "\n":
                i += 1
            continue
        if source.startswith("/*", i):
            end = source.find("*/", i)
            i = n if end == -1 else end + 2
            continue
        out.append(char)
        i += 1

    lines = (line.rstrip() for line in "".join(out).splitlines())
    return "\n".join(line for line in lines if line.strip()) + "\n"


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for example in sorted(EXAMPLES.glob("*.js")):
        text = bundle(example)
        compact = strip_comments(text)

        for target, content in (
            (OUTPUT_DIR / f"{example.stem}-standalone.js", text),
            (OUTPUT_DIR / f"{example.stem}-standalone.min.js", compact),
        ):
            with target.open("w", encoding="utf-8", newline="") as handle:
                handle.write(content)
            print(f"wrote {target.relative_to(ROOT)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
