"""Bundle the Espruino module and an example into one paste-able file.

`require("BTHomeWritable")` only resolves once the module is published to
EspruinoDocs or dropped into the Web IDE's project folder. For bring-up and for
the hardware tests we want something that works with nothing but copy-paste, so
this inlines the module in a closure and appends the example.

`require("BTHome")` is left alone: the Web IDE fetches that one from
espruino.com automatically.

    python -m tools.build_espruino_bundle
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE = ROOT / "espruino" / "BTHomeWritable.js"
EXAMPLES = ROOT / "espruino" / "examples"
OUTPUT_DIR = ROOT / "espruino" / "dist"

HEADER = """/* bthome-writable — {example}, self-contained.
 *
 * GENERATED by tools/build_espruino_bundle.py. Do not edit: change
 * espruino/BTHomeWritable.js or espruino/examples/{example} and rebuild.
 *
 * Paste the whole file into the Espruino Web IDE's right-hand pane and send it
 * to a connected nRF52 board, or push it with tools/espruino_upload.py.
 * `require("BTHome")` is resolved by either; everything else is inlined here.
 *
 * The module is inlined flat rather than wrapped in a closure, on purpose: the
 * Espruino console cannot buffer a single ten-kilobyte statement, so an IIFE
 * around the whole module is silently truncated. Flat means every declaration
 * is its own small statement. It costs a polluted global namespace on a board
 * that is running nothing else.
 */

"""


def bundle(example: Path) -> str:
    module_source = MODULE.read_text(encoding="utf-8")
    example_source = example.read_text(encoding="utf-8")

    # The example requires the module by name; inline it instead.
    example_source = example_source.replace(
        'var bw = require("BTHomeWritable");',
        "var bw = BTHomeWritable;",
    )

    return (
        HEADER.format(example=example.name)
        + "var exports = {};\n\n"
        + module_source
        + "\nvar BTHomeWritable = exports;\n\n"
        + f"/* --- {example.name} --- */\n\n"
        + example_source
    )


def strip_comments(source: str) -> str:
    """Remove comments and blank lines, leaving string literals alone.

    Espruino keeps the source text of every function in RAM, and this module is
    comment-heavy on purpose — which costs more than half the bundle on a
    64 kB device. This is not a minifier: it does not rename or reformat
    anything, so the result still reads like the original.

    It does not recognise regular-expression literals, which would be
    misparsed. Neither the module nor the examples contain one, and
    espruino/test/bundle.test.js runs the stripped bundle to prove it still
    behaves — that check lives on the JS side because it needs a JS engine.
    """
    out: list[str] = []
    i, n = 0, len(source)
    while i < n:
        char = source[i]
        if char in "\"'`":
            quote = char
            out.append(char)
            i += 1
            while i < n:
                if source[i] == "\\":
                    out.append(source[i : i + 2])
                    i += 2
                    continue
                out.append(source[i])
                if source[i] == quote:
                    i += 1
                    break
                i += 1
            continue
        if source.startswith("//", i):
            while i < n and source[i] != "\n":
                i += 1
            continue
        if source.startswith("/*", i):
            end = source.find("*/", i)
            i = n if end == -1 else end + 2
            continue
        out.append(char)
        i += 1

    lines = (line.rstrip() for line in "".join(out).splitlines())
    return "\n".join(line for line in lines if line.strip()) + "\n"


def repl_unsafe_lines(source: str) -> list[tuple[int, str]]:
    """Top-level lines that continue a statement onto the next one.

    The Espruino console evaluates a pasted statement the moment a line ends
    outside any bracket. A top-level statement split across lines is therefore
    executed in halves: the first half raises a syntax error, the second is
    evaluated as a stray expression, and the variable it was meant to define is
    left undefined. Nothing warns — the upload simply produces a board that
    misbehaves later, somewhere else.

    Anything inside brackets is safe, which covers every function body, so in
    practice this only catches wrapped top-level assignments — exactly what a
    formatter introduces when a line grows past its limit.
    """
    offenders: list[tuple[int, str]] = []
    depth = 0
    quote: str | None = None

    for lineno, line in enumerate(source.splitlines(), 1):
        depth_at_start = depth
        i = 0
        while i < len(line):
            char = line[i]
            if quote:
                if char == "\\":
                    i += 2
                    continue
                if char == quote:
                    quote = None
            elif char in "\"'`":
                quote = char
            elif char in "([{":
                depth += 1
            elif char in ")]}":
                depth -= 1
            i += 1

        stripped = line.strip()
        at_top_level = depth_at_start == 0 and depth == 0 and stripped
        if at_top_level and not stripped.endswith((";", "{", "}")):
            offenders.append((lineno, stripped))
    return offenders


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for example in sorted(EXAMPLES.glob("*.js")):
        text = bundle(example)
        compact = strip_comments(text)

        offenders = repl_unsafe_lines(compact)
        if offenders:
            print(f"{example.name}: top-level statements split across lines:")
            for lineno, line in offenders:
                print(f"  line {lineno}: {line}")
            raise SystemExit(
                "these would be evaluated in halves by the Espruino console; "
                "keep each top-level statement on one line"
            )

        for target, content in (
            (OUTPUT_DIR / f"{example.stem}-standalone.js", text),
            (OUTPUT_DIR / f"{example.stem}-standalone.min.js", compact),
        ):
            with target.open("w", encoding="utf-8", newline="") as handle:
                handle.write(content)
            print(f"wrote {target.relative_to(ROOT)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
